Guix: upgrade to 1.5.0.
If we build the website right before this commit and then build it
again in this commit without the Guix wrapper modifications, we have
the following error with 'make serve':

    guix shell: error: texlive-texinfo: unknown package
    make: *** [Makefile:887: pages/manual/gnuboot.html] Error 1

This is becase at the previous commit, the topdir config.sh was
generated and therefor contains the Guix 1.4.0 commit.

And so if we do nothing about it, since the topdir config.sh file do
exist, the wrapper will still use Guix 1.4.0.

We don't need to care about older Guix revisions since the guix
wrapper wasn't used with revisions older than Guix 1.4.0.

However even if we detect that the config.sh file has Guix 1.4.0
starting from now, it would still break if we generate the config.sh
file now and then go back to an older GNU Boot revision (which cannot
detect if the Guix revision matches with what is in config.sh). This
could then silently break git bisect.

Since we can't go back in the past and modify the git history to add
this detection, the config.sh file was simply renamed to conf.sh and
the check to detect different Guix revisions was added to avoid having
to rename the file again in the future.

As for the error message, we need to output to stderr to make sure it
is seen during the build of the website, otherwise the message could
end up in a variable when using `` in Makefiles or $() in shell
scripts.

Signed-off-by: Denis 'GNUtoo' Carikli <GNUtoo@cyberdimension.org>

diff --git a/resources/wrapper/guix b/resources/wrapper/guix
--- a/resources/wrapper/guix
+++ b/resources/wrapper/guix
@@ -32,15 +32,31 @@ eval "$("${topdir}"/guix-revision.sh print-shell)"
 source "${topdir}"/resources/scripts/misc/sysexits.sh
 
 # We need ${GUIX_BUILD_MAX_CORES}
-if [ ! -f "${topdir}"/config.sh ] ; then
-    echo "config.sh not found in GNU Boot top directory (""${topdir}"")"
-    echo "To fix it run the following commands:"
-    echo "    cd ""${topdir}"""
-    echo "    ./autogen.sh"
-    echo "    ./configure"
+if [ ! -f "${topdir}"/conf.sh ] ; then
+    printf "\n" > /dev/stderr
+    printf "ERROR: conf.sh not found in GNU Boot top directory (%s)\n" \
+	   "${topdir}" > /dev/stderr
+    printf "To fix it run the following commands:\n" > /dev/stderr
+    printf "    cd '%s'\n" \
+	   "${topdir}" > /dev/stderr
+    printf "    ./autogen.sh\n" > /dev/stderr
+    printf "    ./configure\n" > /dev/stderr
     exit "${EX_NOINPUT}"
 fi
-source "${topdir}"/config.sh
+
+source "${topdir}"/conf.sh
+
+if [ "${GUIX_REVISION}" != "230aa373f315f247852ee07dff34146e9b480aec" ] ; then
+    printf "\n" > /dev/stderr
+    printf "ERROR: The conf.sh file that is in %s is outdated.\n" \
+	   "${topdir}" > /dev/stderr
+    printf "To fix it run the following commands:\n" > /dev/stderr
+    printf "    cd '%s'\n" \
+	   "${topdir}" > /dev/stderr
+    printf "    ./autogen.sh\n" > /dev/stderr
+    printf "    ./configure\n" > /dev/stderr
+    exit "${EX_NOINPUT}"
+fi
 
 # We need -C resources/wrapper/channels.scm to make sure to only use
 # the default channels provided by Guix.
